build:
  dependencies:
    override:
    - make deps generate

  environment:
    go: go1.9

  nodes:
    analysis:
      tests:
        override:
        - go-scrutinizer-run
        - golint-run
        - govet-run

  tests:
    override:
    - make test

checks:
  go: true
