language: go

go:
- 1.7.x
- 1.8.x
- 1.9.x
- master

matrix:
  allow_failures:
  - go: 1.7.x # problems with go get dep
  - go: 1.8.x # problems with go generate
  - go: master
  fast_finish: true

sudo: false

before_install:
- make tools

install:
- make deps

script:
- make test-with-race

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
