language: go

go:
- 1.7.x
- 1.8.x
- 1.9.x
- master

matrix:
  allow_failures:
  - go: 1.7.x # problems with go get dep
  - go: 1.8.x # problems with go generate
  - go: master
  fast_finish: true

sudo: false

before_install:
- wget -q -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
- chmod +x dep && mv dep "${GOPATH}"/bin
- make tools
- go get github.com/mattn/goveralls
- export GO_TEST_COVERAGE_FILENAME='coverage.out'

install:
- make deps generate

script:
- make test-with-coverage-profile ARGS='-timeout=1s'

after_success:
- goveralls -service=travis-ci -coverprofile="${GO_TEST_COVERAGE_FILENAME}"
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
