version: "3"

services:
  db:
    image: postgres:10-alpine
    env_file: .env
    ports:
    - "5432:5432"
    restart: always

#  discovery:
#    image: consul:latest
#    environment:
#      CONSUL_BIND_INTERFACE: eth0
#    networks:
#    - host
#    ports:
#    -
#    restart: always
#
#  service:
#
#  server:
#    image: nginx:1-alpine
#    ports:
#    - 8080:80
#    restart: always

volumes:
  db-data:
    driver: local
