version: "3"

services:
  db:
    # https://hub.docker.com/_/postgres/
    image: postgres:10-alpine
    env_file: .env
    ports:
    - 5432:5432
    restart: always
    volumes:
    - pgdata:${PGDATA}

  service:
    build:
      args: { QUICK: "true" }
      context: ../.
      dockerfile: ./env/Dockerfile
    depends_on:
    - db
    env_file: .env
    restart: always
    ports:
    - 8080:${PORT}

  server:
    # https://hub.docker.com/_/nginx/
    image: kamilsk/nginx:alpine
    entrypoint: /bin/sh -c 'envsubst < /etc/nginx/conf.d/service.template > /etc/nginx/conf.d/service.conf && /entrypoint.sh'
    env_file: .env
    ports:
    - 8081:${DOMAIN_PORT}
    restart: always
    volumes:
    - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/service.conf.template:/etc/nginx/conf.d/service.template:ro
    - certificates:/etc/nginx/ssl
    - le_challenge:/usr/share/sites/${DOMAIN_NAME}

volumes:
  pgdata:
    driver: local

  certificates:
    driver: local

  le_challenge:
    driver: local
