version: "3"

services:
  db:
    # https://hub.docker.com/_/postgres/
    image: postgres:10-alpine
    env_file: .env
    ports:
    - "5432:5432"
    restart: always

#  discovery:
#    image: consul:latest
#    environment:
#      CONSUL_BIND_INTERFACE: eth0
#    networks:
#    - host
#    ports:
#    -
#    restart: always

  service:
    build:
      args: { QUICK: "true" }
      context: ../.
      dockerfile: ./env/Dockerfile
    depends_on:
    - db
    env_file: .env
    ports:
    - "8080:8080"

  server:
    # https://hub.docker.com/_/nginx/
    image: nginx:1-alpine
    env_file: .env
    command: sh -c "envsubst < /etc/nginx/conf.d/service.template > /etc/nginx/conf.d/service.conf && nginx -g 'daemon off;'"
    ports:
    - "8081:80"
    - "8082:8080"
    restart: always
    volumes:
    - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/service.conf.template:/etc/nginx/conf.d/service.template:ro

volumes:
  db-data:
    driver: local
